
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-nose-tests
spec:
  steps:
    - name: run-tests
      image: python:3.11
      script: |
        #!/bin/bash
        pip install nose
        nosetests tests/

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: clean
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up the environment..."
